const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const reTypePassword = "Retype Password";
const name = "Name";
const nameHint = "Adil Shinwari";
const passwordHint = "********";
const forgetPass = 'Forget Password';
const login = 'Log in';
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = 'Privacy Policy';
const termsAndConditions = 'Terms And Conditions';

const alreadyAcount = 'Already have an account? ';
